[project]
name = "robotbench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dmytro Bahatskyi", email = "dm.bagatsky@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "lerobot[dataset-viz]>=0.6.1",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "plotly>=7.1.0",
    "pydantic>=2.13.5",
    "streamlit>=1.64.0",
]

[project.scripts]
robotbench = "robotbench:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
